platform :ios, '9.0'
inhibit_all_warnings!

source 'https://cdn.cocoapods.org/'

target 'oc-quick-start' do
 
pod 'JSONativeUI', :path => '/Users/lion/sourcetree-workspace/librarys/JSONativeUI'
  

end
